In [75]:
import os
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
from torchvision import transforms
import torch

In [20]:
def load_data(radar_dir="data/Dataset3/radar"):
        """Set features and targets"""
        features_dir = "data/Dataset3/himawari"
        result = []
        
        for root, dirs, files in os.walk(radar_dir):
            for file in files:
                if file.endswith(".tif"):
                    path = os.path.join(root, file)
                    folder_path = os.path.dirname(path)
                    folder_path = "/".join(folder_path.split("/")[-4:])
                    # result.append((f"data/Dataset3/himawari/{folder_path}", f"data/Dataset3/radar/{folder_path}"))
                    result.append((features_dir + "/" + folder_path, radar_dir + "/" + folder_path))
                    # /mnt/banana/k66/pad/rainfall_estimation/data//Dataset3/himawari/k66/pad/rainfall_estimation/data//Dataset3/radar/2020/10/18/12
        
        return result

In [116]:
def image_from_dir(feature_dir)->torch.Tensor:
    """Stack all image in a directory"""
    res = []

    for path in os.listdir(feature_dir):
        image_path = os.path.join(feature_dir, path)
        image = Image.open(image_path)
        tensor_image = transforms.ToTensor()(image).squeeze()
        res.append(tensor_image)

    return torch.stack(res)

In [90]:
tmp = image_from_dir("data/Dataset3/radar/2020/10/20/03")
print(tmp.shape)

torch.Size([1, 512, 512])


In [124]:
result=load_data()

In [125]:
stack = []
for input_dir, output_dir in result:
    stack.append(image_from_dir(output_dir))
stack = torch.stack(stack)

stack

tensor([[[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          ...,
          [-9.9999e+04, -9.9999e+04, -9.9999e+04,  ...,  6.2500e+00,
            7.7500e+00,  8.2500e+00],
          [-9.9999e+04, -9.9999e+04, -9.9999e+04,  ...,  6.2500e+00,
            5.7500e+00,  5.7500e+00],
          [-9.9999e+04, -9.9999e+04, -9.9999e+04,  ...,  5.2500e+00,
            6.7500e+00,  4.1200e+00]]],


        [[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
            0.0000e+00,  0.0000e+00],
          ...,
   

In [126]:
mean = np.mean(stack.numpy(), axis=(0, 2, 3))
std = np.std(stack.numpy(), axis=(0, 2, 3))
mean, std

(array([-2964.3228], dtype=float32), array([16963.572], dtype=float32))

In [127]:
img = image_from_dir("data/Dataset3/himawari/2020/10/20/03")
print(img.shape)
# img = transforms.ToPILImage()(img)
print(img.size)
# img = transforms.ToTensor()(img)
# img = transforms.Normalize(mean=[244.4633 , 240.71112, 241.49652, 241.35864, 241.24358, 241.72144, 242.25307, 241.99025, 243.02498, 245.28816], 
                        #    std=[25.258839, 23.773561, 25.376684, 24.331238, 22.94927 , 23.437948, 25.545214, 25.882654, 26.089962, 26.234522])(img)
img = transforms.Normalize(mean=[-2964.3228], std=[16963.572])(img)
img

torch.Size([10, 512, 512])
<built-in method size of Tensor object at 0x1362315e0>


tensor([[[0.1888, 0.1888, 0.1888,  ..., 0.1887, 0.1887, 0.1887],
         [0.1888, 0.1888, 0.1888,  ..., 0.1887, 0.1887, 0.1887],
         [0.1888, 0.1888, 0.1888,  ..., 0.1887, 0.1887, 0.1887],
         ...,
         [0.1882, 0.1882, 0.1882,  ..., 0.1867, 0.1867, 0.1867],
         [0.1882, 0.1882, 0.1882,  ..., 0.1871, 0.1871, 0.1871],
         [0.1882, 0.1882, 0.1882,  ..., 0.1871, 0.1871, 0.1871]],

        [[0.1902, 0.1902, 0.1902,  ..., 0.1913, 0.1913, 0.1913],
         [0.1902, 0.1902, 0.1902,  ..., 0.1913, 0.1913, 0.1913],
         [0.1901, 0.1901, 0.1901,  ..., 0.1911, 0.1911, 0.1911],
         ...,
         [0.1902, 0.1902, 0.1902,  ..., 0.1866, 0.1866, 0.1866],
         [0.1902, 0.1902, 0.1902,  ..., 0.1870, 0.1870, 0.1870],
         [0.1902, 0.1902, 0.1902,  ..., 0.1870, 0.1870, 0.1870]],

        [[0.1903, 0.1903, 0.1903,  ..., 0.1916, 0.1916, 0.1916],
         [0.1903, 0.1903, 0.1903,  ..., 0.1916, 0.1916, 0.1916],
         [0.1903, 0.1903, 0.1903,  ..., 0.1914, 0.1914, 0.